### ISSUE TITLE
Mixed Up "set_version"

### ISSUE THREAD

**Issue by Brauadler** [MailCleaner/Updater4MC#66]
Hello John,

just a small note: 
In Updater4mc updates 76 and 77, the version of Mailcleaner was set incorrectly. This could be confusing for people who don't follow the repository. The update 76 from October had the following setting `set_version 2022 11 18 "mailcleaner-library 1.0.6"` (_now the date is in the past and a change not neccessary anymore_) and the update 77 a setting of `set_version 2022 02 28 "ClamAV 0.103.7"` which in my instance triggers a combo of both (see picture).

![grafik](https://user-images.githubusercontent.com/95625809/205857224-00f0c670-99a2-4a94-971a-2a7eac2385c0.png)

**Comment by JohnMertz** [comment]
Hello,

Sorry about that. I copied the script from the last ClamAV upgrade and changed the version numbers, but missed the date.

These version numbers in the WebUI are completely cosmetic, so it will not cause any problems. The mix is because 'set_version' writes `/usr/mailcleaner/etc/mailcleaner/version.def` directly which is the 'Version'. It appends the patch level to a database table only if it is newer than the last update.

I updated the script so that it will work for anyone who has not installed it yet. For anyone who has, it will not run again. I could release an update which does nothing but increments this number, but that is probably not necessary. If you would like to clear it up on your machine, you could manually write it to the db:

```
echo "insert into update_patch(id, date, time, status, description) values('20221206', '2022-12-06', '12:00:00', 'OK', 'ClamAV 0.103.7');" | mc_mysql -s mc_config
```
